# Generated by Django 2.2.2 on 2020-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ipadress',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ip Adress'),
        ),
    ]
